### ISSUE TITLE
Issues getting it working on RM2?

### ISSUE THREAD

**Issue by koshibb** [ddvk/remarkable2-framebuffer#90]
I can't seem to find the package  using the pkg info command. Is this not available anymore?

**Comment by Eeems** [comment]
It's part of the `display` package in toltec.

**Comment by koshibb** [comment]
Interesting. So I am attempting to install remux now, and I can't seem to get it running. Any suggestions?

**Comment by Eeems** [comment]
I would recommend closing this issue an opening a discussion on the toltec repo: https://github.com/toltec-dev/toltec/discussions
That or asking in the community discord: [![Discord](https://img.shields.io/discord/385916768696139794.svg?label=reMarkable&logo=discord&logoColor=ffffff&color=7389D8&labelColor=6A7EC2)](https://discord.gg/ATqQGfu)

I would also recommend including more information about what you've actually done so far. Otherwise it'll be difficult to recommend what to do next.
